# (generated with --quick)

from typing import Any
import unittest.case

Config: Any
Utils: Any
unittest: module
yaml: module

class TestConfig(unittest.case.TestCase):
    configFilePath: Any
    def _write_config(self, config) -> None: ...
    def test_cannot_load_again(self) -> None: ...
    def test_class_method_generation(self) -> None: ...
    def test_empty_config(self) -> None: ...
    def test_file_not_found(self) -> None: ...
    def test_invalid_yaml(self) -> None: ...
