# (generated with --quick)

from typing import Any
import unittest.case

__author__: str
__date__: str
__license__: str
__revision__: str
__version__: str
generators: Any
itertools: module
unittest: module

class TestGenerators(unittest.case.TestCase):
    def test_LFSR(self) -> None: ...
    def test_ackermann(self) -> None: ...
    def test_ackermann_fast(self) -> None: ...
    def test_ackermann_naive(self) -> None: ...
    def test_ackermann_slow(self) -> None: ...
    def test_carmichael(self) -> None: ...
    def test_composite(self) -> None: ...
    def test_eratosthenes(self) -> None: ...
    def test_fermat(self) -> None: ...
    def test_fibonacci(self) -> None: ...
    def test_identity(self) -> None: ...
    def test_mersenne(self) -> None: ...
    def test_triangular_numbers(self) -> None: ...
