# (generated with --quick)

argparse: module
args: argparse.Namespace
os: module
subprocess: module
sys: module
workdir: str

def build() -> None: ...
def main() -> None: ...
def setup() -> None: ...
def sign() -> None: ...
def verify() -> None: ...
