# (generated with --quick)

from typing import Any

impl: Any
itertools: module
logging: module
pytest: Any
re: module

class TestCallbackUserAgentParser:
    def test_explicit_name(self) -> None: ...
    def test_passed_input(self) -> None: ...
    def test_returns_on_success(self) -> None: ...
    def test_undefined_name(self) -> None: ...

class TestDecorators:
    test_regex_us_parser: Any
    def test_ua_parser(self, monkeypatch) -> None: ...

class TestParserSet:
    def test_cannot_parse(self) -> None: ...
    def test_error_while_parsing(self, caplog) -> None: ...
    def test_optimizing(self) -> None: ...
    def test_valid(self) -> None: ...

class TestRegexUserAgentParser:
    test_invalid: Any
    test_valid: Any
    def test_explicit_name(self) -> None: ...
    def test_mixed_captures(self) -> None: ...
    def test_named_captures(self) -> None: ...
    def test_positional_captures(self) -> None: ...
    def test_undefined_name(self) -> None: ...
