# (generated with --quick)

from typing import Dict, Iterator, List

__author__: str
__date__: str
__license__: str
__revision__: str
__version__: str
itertools: module
math: module
polys: Dict[int, List[int]]

def LFSR(m: int) -> Iterator[int]: ...
def ackermann(m: int) -> Iterator[int]: ...
def ackermann_fast(m: int, n: int) -> int: ...
def ackermann_naive(m: int) -> Iterator[int]: ...
def ackermann_slow(m: int, n: int) -> int: ...
def carmichael() -> Iterator[int]: ...
def composite() -> Iterator[int]: ...
def eratosthenes() -> Iterator[int]: ...
def fermat() -> Iterator[int]: ...
def fibonacci() -> Iterator[int]: ...
def identity() -> Iterator[int]: ...
def log_gen() -> Iterator[int]: ...
def mersenne() -> Iterator[int]: ...
def triangular_numbers() -> Iterator[int]: ...
