# (generated with --quick)

import sqlite3.dbapi2
from typing import Any, Coroutine, Optional, Type, Union

def __make_tables(path) -> None: ...
def connect(database: Union[bytes, str], timeout: float = ..., detect_types: int = ..., isolation_level: Optional[str] = ..., check_same_thread: bool = ..., factory: Optional[Type[sqlite3.dbapi2.Connection]] = ..., cached_statements: int = ..., uri: bool = ...) -> sqlite3.dbapi2.Connection: ...
def make_tables(path, loop) -> Coroutine[Any, Any, None]: ...
