# (generated with --quick)

from typing import Any

requests: module
urllib: module
verify_data: Any

def __getattr__(name) -> Any: ...
def download_file(url, save_folder = ..., username = ..., password = ...) -> str: ...
def download_mimic3_files(physionet_filenames = ...) -> None: ...
def verify_physionet_credentials(username, password) -> bool: ...
