# (generated with --quick)

from typing import Any

datasets: Any
warnings: module
wt: Any

def test_constant_warning() -> None: ...
def test_exception() -> None: ...
def test_implied() -> None: ...
def test_index() -> None: ...
def test_not_implied() -> None: ...
