# (generated with --quick)

from typing import Any, Tuple

check_random_state: Any
make_regression: Any
np: module
shuffle: Any

def _checkParam(n_samples = ..., n_features = ..., n_redundant = ..., n_strel = ..., n_repeated = ..., flip_y = ..., noise = ..., partition = ..., **kwargs) -> None: ...
def _combFeat(n, size, strRelFeat, randomstate) -> Any: ...
def _dummyFeat(n, randomstate) -> Any: ...
def _fillVariableSpace(X_informative, random_state, n_samples = ..., n_features = ..., n_redundant = ..., n_strel = ..., n_repeated = ..., noise = ..., partition = ..., **kwargs) -> Any: ...
def _repeatFeat(feats, i, randomstate) -> Any: ...
def genClassificationData(n_samples = ..., n_features = ..., n_redundant = ..., n_strel = ..., n_repeated = ..., noise = ..., flip_y = ..., random_state = ..., partition = ...) -> Tuple[Any, Any]: ...
def genOrdinalRegressionData(n_samples = ..., n_features = ..., n_redundant = ..., n_strel = ..., n_repeated = ..., noise = ..., random_state = ..., partition = ..., n_target_bins = ...) -> Tuple[Any, Any]: ...
def genRegressionData(n_samples = ..., n_features = ..., n_redundant = ..., n_strel = ..., n_repeated = ..., noise = ..., random_state = ..., partition = ...) -> Tuple[Any, Any]: ...
