# (generated with --quick)

from typing import Any, List

SECONDS_VALUES: List[int]
json: module
re: module

def convert_int_to_str(number: int, char: str = ...) -> str: ...
def convert_seconds_to_str(sec: float) -> str: ...
def convert_str_to_seconds(duration: str) -> int: ...
def load_json(filename: str) -> Any: ...
def save_json(data, filename: str, should_be_sorted = ...) -> None: ...
